export const USER_ACTION_TYPES = {
  ADD_USER_TO_TEAM1: 'ADD_USER_TO_TEAM1',
  ADD_USER_TO_TEAM2: 'ADD_USER_TO_TEAM2',
  REMOVE_USER_FROM_TEAM1: 'REMOVE_USER_FROM_TEAM1',
  REMOVE_USER_FROM_TEAM2: 'REMOVE_USER_FROM_TEAM2',
};
