// initial state
export const initialState = {
  team1: [],
  team1Score: 0,
  team1RoundWins: 0,
  team2: [],
  team2Score: 0,
  team2RoundWins: 0,
  cardpacks: [],
  selectedCardpacks: [],
  turnTime: 60,
  cardCount: 60,
  roundCount: 0,
  round1MVP: "",
  round2MVP: "",
  round3MVP: "",
  fastestTalker: "",
  bestOneWordPony: "",
  bestHandAndBodyFlapper: "",
  fastestRightAnswer: "",
  deck: [],
  discardPile: [],
  activeCard: {},
  user: {},
};
